/**
 * The render registry — every capture this machine can open, in one list.
 *
 * lib/assets.ts holds the captures that ship with the repo, hand-tuned because
 * each one needed a transform checked by eye. Everything the user generates
 * lands in public/generated/<id>/ and is described entirely by the scene.json
 * that environment-builder writes next to the assets, so it needs no code
 * change to become selectable. This module is the bridge: it reads those
 * scene.json files, turns each into the same `AssetSet` shape the loaders
 * already consume, and merges them with the hardcoded sets.
 *
 * SERVER ONLY. It touches node:fs, so it is imported from route handlers and
 * nowhere else; the browser gets the result through /api/renders.
 *
 * Where a generated id collides with a hardcoded one, the hardcoded definition
 * wins. That is not arbitrary: maple-street exists in both, and its checked-in
 * entry carries a colliderPlacement that was verified against the walls on the
 * plan screen, which scene.json itself flags as UNVERIFIED. The scene.json is
 * still read for the facts it does own — when it was made, how big it is.
 */

import { readFile, readdir, stat } from 'node:fs/promises';
import { join, resolve } from 'node:path';

import { ASSET_SETS, type AssetSet, type SplatPlacement } from './assets';

/**
 * Where a capture came from.
 *
 * 'uploaded' is not a cosmetic distinction. A generated capture's placement is
 * derived from Marble's own semantics_metadata and its collider shares the
 * splat's frame; an uploaded one's placement was measured and fitted here, and
 * its collider is the frame rather than something transformed into it. The two
 * are read out of scene.json differently below, and the list says which is
 * which because it changes what a misaligned room means.
 */
export type RenderSource = 'builtin' | 'generated' | 'uploaded';

export type RenderSummary = {
  id: string;
  label: string;
  description: string;
  source: RenderSource;
  /** ISO timestamp from scene.json, or the folder's mtime. Null for builtins. */
  createdAt: string | null;
  /** Size of the splat actually on disk, for an honest "this is a 60 MB fetch". */
  splatBytes: number | null;
  approxSplats: number | null;
  colliderTriangles: number | null;
  /** Public URL of a still, when the capture has one. */
  thumbnail: string | null;
  /**
   * Whether the files are really here. Several captures are derived from local
   * source data and are gitignored, so a fresh clone lists them and 404s on the
   * first fetch; the list says so instead of letting the user find out in 3D.
   */
  present: boolean;
  /** Registered client-side so getAssetSet(id) resolves this render. */
  assetSet: AssetSet;
};

const PUBLIC_DIR = resolve(process.cwd(), 'public');
const GENERATED_DIR = join(PUBLIC_DIR, 'generated');

/** Written by the create flow; see app/api/renders/jobs.ts. */
const THUMBNAIL_NAMES = ['thumbnail.jpg', 'thumbnail.jpeg', 'thumbnail.png', 'thumbnail.webp'];

/* -------------------------------------------------------------------------- */
/* scene.json                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * The subset of scene.json this module relies on.
 *
 * Deliberately partial and all-optional: scene.json is written by a pipeline
 * that will keep growing, and a capture generated by an older version of it
 * must still show up in the list rather than throwing the whole route.
 */
type SceneJson = {
  /** 'world-labs-marble' or 'user-upload'. Absent on the earliest captures. */
  source?: unknown;
  generatedAt?: unknown;
  prompt?: unknown;
  world?: { caption?: unknown } | unknown;
  provenance?: unknown;
  splatTransform?: unknown;
  /** Written by the upload flow; absent on a Marble capture. See below. */
  colliderTransform?: unknown;
  files?: unknown;
};

function asRecord(value: unknown): Record<string, unknown> | null {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function asString(value: unknown): string | null {
  return typeof value === 'string' && value.trim() ? value.trim() : null;
}

function asNumber(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function asVec3(value: unknown): [number, number, number] | null {
  if (!Array.isArray(value) || value.length !== 3) return null;
  const [x, y, z] = value;
  if (![x, y, z].every((n) => typeof n === 'number' && Number.isFinite(n))) return null;
  return [x as number, y as number, z as number];
}

const IDENTITY: SplatPlacement = { position: [0, 0, 0], rotation: [0, 0, 0], scale: 1 };

function placementFrom(value: unknown): SplatPlacement {
  const record = asRecord(value);
  if (!record) return IDENTITY;
  return {
    position: asVec3(record.position) ?? IDENTITY.position,
    rotation: asVec3(record.rotation) ?? IDENTITY.rotation,
    scale: asNumber(record.scale) ?? 1,
  };
}

/**
 * Splat count from the density key Marble named the export with.
 *
 * The exact count is in the SPZ header, but that header is behind a gzip
 * stream at the front of a file that can be hundreds of megabytes, and this
 * runs for every capture on every page load. `500k` is close enough to warn
 * someone that a capture is heavy, which is all the number is for.
 */
function splatsFromSpzKey(key: string | null): number | null {
  if (!key) return null;
  const match = /^(\d+)([km])$/i.exec(key);
  if (!match) return null;
  return Number(match[1]) * (match[2].toLowerCase() === 'm' ? 1_000_000 : 1_000);
}

/** One line of prose for the list row, in descending order of usefulness. */
function describeScene(
  scene: SceneJson,
  provenance: Record<string, unknown> | null,
  source: RenderSource,
): string {
  const world = asRecord(scene.world);
  const stated =
    asString(provenance?.description) ?? asString(scene.prompt) ?? asString(world?.caption);
  if (stated) return stated;
  // An upload has no prompt and no caption to fall back on, and claiming it
  // came out of Marble would be a plain untruth on the row.
  return source === 'uploaded'
    ? 'Uploaded splat and collision mesh.'
    : 'Generated by World Labs Marble.';
}

async function fileSize(path: string): Promise<number | null> {
  try {
    const info = await stat(path);
    return info.isFile() ? info.size : null;
  } catch {
    return null;
  }
}

async function firstExisting(dir: string, names: readonly string[]): Promise<string | null> {
  for (const name of names) {
    if ((await fileSize(join(dir, name))) !== null) return name;
  }
  return null;
}

/* -------------------------------------------------------------------------- */
/* discovery                                                                  */
/* -------------------------------------------------------------------------- */

async function readGeneratedRender(id: string): Promise<RenderSummary | null> {
  const dir = join(GENERATED_DIR, id);

  let scene: SceneJson;
  try {
    scene = JSON.parse(await readFile(join(dir, 'scene.json'), 'utf8')) as SceneJson;
  } catch {
    // A directory mid-generation, or one whose scene.json never got written
    // because the build failed. Not a render yet, so not in the list.
    return null;
  }

  const provenance = asRecord(scene.provenance);
  const files = asRecord(scene.files);
  const splatFile = asRecord(files?.splat);
  const colliderFile = asRecord(files?.collider);

  const splatName = asString(splatFile?.file) ?? 'room.spz';
  const colliderName = asString(colliderFile?.file) ?? 'collider.glb';
  const splatBytes = (await fileSize(join(dir, splatName))) ?? asNumber(splatFile?.bytes);
  const colliderOnDisk = (await fileSize(join(dir, colliderName))) !== null;

  const placement = placementFrom(scene.splatTransform);
  const source: RenderSource = asString(scene.source) === 'user-upload' ? 'uploaded' : 'generated';
  const description = describeScene(scene, provenance, source);
  const thumbnail = await firstExisting(dir, THUMBNAIL_NAMES);

  /* An uploaded capture counted its own splats out of the file header, which is
     exact. A generated one has only the density key Marble named the export
     with, which is a round number by construction. */
  const approxSplats =
    asNumber(splatFile?.splats) ?? splatsFromSpzKey(asString(splatFile?.spzKey));

  const assetSet: AssetSet = {
    id,
    label: asString(provenance?.name) ?? id,
    description,
    splat: `/generated/${id}/${splatName}`,
    splatFallback: null,
    collider: `/generated/${id}/${colliderName}`,
    objects: `/generated/${id}/objects.json`,
    placement,
    /* Stated by the capture when it knows, inferred when it does not.
       An upload writes `colliderTransform` explicitly — usually identity,
       because an uploaded collider IS the world the splat was fitted into and
       transforming it would move the walls out from under the fit. A Marble
       capture writes no such key: it returns the collider in the same
       pre-metric OpenCV frame as the splat, so it takes the splat's transform.
       scene.json says so and flags the scale half unverified; applying it is
       still much closer than leaving a 1.9x-too-small mesh at the origin. */
    colliderPlacement:
      scene.colliderTransform === undefined ? placement : placementFrom(scene.colliderTransform),
    ...(approxSplats === null ? {} : { approxSplats }),
  };

  return {
    id,
    label: assetSet.label,
    description,
    source,
    createdAt: asString(scene.generatedAt),
    splatBytes,
    approxSplats: assetSet.approxSplats ?? null,
    colliderTriangles: asNumber(colliderFile?.triangles),
    thumbnail: thumbnail ? `/generated/${id}/${thumbnail}` : null,
    present: splatBytes !== null && colliderOnDisk,
    assetSet,
  };
}

/** Public URL -> path under public/. Returns null for anything off-site. */
function publicPath(url: string): string | null {
  return url.startsWith('/') ? join(PUBLIC_DIR, url.slice(1)) : null;
}

async function summariseBuiltin(set: AssetSet): Promise<RenderSummary> {
  const splatUrl = set.splat;
  const splatPath = publicPath(splatUrl);
  let splatBytes = splatPath ? await fileSize(splatPath) : null;

  // The fallback is not a lesser copy, it is the file that actually ships for
  // the fixture room - reporting "missing" for a capture that loads fine would
  // be worse than reporting the fallback's size.
  if (splatBytes === null && set.splatFallback) {
    const fallbackPath = publicPath(set.splatFallback);
    splatBytes = fallbackPath ? await fileSize(fallbackPath) : null;
  }

  const colliderPath = publicPath(set.collider);
  const colliderBytes = colliderPath ? await fileSize(colliderPath) : null;

  return {
    id: set.id,
    label: set.label,
    description: set.description,
    source: 'builtin',
    createdAt: null,
    splatBytes,
    approxSplats: set.approxSplats ?? null,
    colliderTriangles: null,
    thumbnail: null,
    present: splatBytes !== null && colliderBytes !== null,
    assetSet: set,
  };
}

/** Every capture — built-in, generated and uploaded — newest first. */
export async function listRenders(): Promise<RenderSummary[]> {
  const builtins = await Promise.all(Object.values(ASSET_SETS).map(summariseBuiltin));
  const byId = new Map(builtins.map((entry) => [entry.id, entry]));

  let entries: string[] = [];
  try {
    const dirents = await readdir(GENERATED_DIR, { withFileTypes: true });
    entries = dirents.filter((d) => d.isDirectory()).map((d) => d.name);
  } catch {
    // No public/generated yet - nothing has been generated on this machine.
  }

  const discovered = (await Promise.all(entries.map(readGeneratedRender))).filter(
    (entry): entry is RenderSummary => entry !== null,
  );

  for (const entry of discovered) {
    const builtin = byId.get(entry.id);
    if (!builtin) {
      byId.set(entry.id, entry);
      continue;
    }
    // Hand-tuned definition, plus the facts only the folder knows.
    byId.set(entry.id, {
      ...builtin,
      createdAt: entry.createdAt,
      splatBytes: entry.splatBytes ?? builtin.splatBytes,
      colliderTriangles: entry.colliderTriangles,
      thumbnail: entry.thumbnail,
      present: entry.present,
    });
  }

  // Made on this machine above shipped with the repo, newest first inside
  // each group — the thing someone just made is the thing they came back for,
  // and whether they generated it or uploaded it does not change that.
  return [...byId.values()].sort((a, b) => {
    const aBuiltin = a.source === 'builtin';
    const bBuiltin = b.source === 'builtin';
    if (aBuiltin !== bBuiltin) return aBuiltin ? 1 : -1;
    if (a.createdAt && b.createdAt) return b.createdAt.localeCompare(a.createdAt);
    return a.label.localeCompare(b.label);
  });
}

/** One capture by id, or null. Same shape as a row of `listRenders`. */
export async function getRender(id: string): Promise<RenderSummary | null> {
  return (await listRenders()).find((entry) => entry.id === id) ?? null;
}
